# top level stuff you probably don't need to touch
highlighter: rouge
markdown: rdiscount
rdiscount:
  extensions: [smart]
permalink: /:title.html
paginate: 5
gems: [jekyll-paginate]
port: 3000
safe: true


# edit here to achieve your personal greatness
url: http://josephgodwinkimani.github.io
baseurl: ''
hosturl: https://ghatechnologies.info
title: Joseph Godwin Kimani
author: josephgodwinkimani
description: Engaging Purposeful and Creative
avatar: profile2.png
email: josephgodwinke@gmail.com
github: josephgodwinkimani # username
twitter: josephgodwinke
linkedin: josephgodwinke
stackoverflow: users/5194112/joseph-godwinke   #e.g: users/2735833/proton1h1
steam: gooer254
bitbucket: josephgodwinkimani
csgo-stats: gooer254
#Comment out if you don't want disqus 
disqus: josephgodwinke
google_analytics: UA-71809558-3


# needed for travis-ci build
exclude: [vendor]
